// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0oyUz_jC0iJXXWZYiaCV31wE33EYArbA',
    appId: '1:86327090390:web:9d38292656c502bafc3d77',
    messagingSenderId: '86327090390',
    projectId: 'loan-system-37b90',
    authDomain: 'loan-system-37b90.firebaseapp.com',
    storageBucket: 'loan-system-37b90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgev9pG9v3foNQVBguHxd19fmn8if7EWc',
    appId: '1:86327090390:android:3c2fbe93ae2db78bfc3d77',
    messagingSenderId: '86327090390',
    projectId: 'loan-system-37b90',
    storageBucket: 'loan-system-37b90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5a5hThhyU1EZP1wF0DFdwoq_UF7GaEzU',
    appId: '1:86327090390:ios:c2579b7c0c2f8d2ffc3d77',
    messagingSenderId: '86327090390',
    projectId: 'loan-system-37b90',
    storageBucket: 'loan-system-37b90.firebasestorage.app',
    iosBundleId: 'com.example.pocketGrowth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5a5hThhyU1EZP1wF0DFdwoq_UF7GaEzU',
    appId: '1:86327090390:ios:c2579b7c0c2f8d2ffc3d77',
    messagingSenderId: '86327090390',
    projectId: 'loan-system-37b90',
    storageBucket: 'loan-system-37b90.firebasestorage.app',
    iosBundleId: 'com.example.pocketGrowth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0oyUz_jC0iJXXWZYiaCV31wE33EYArbA',
    appId: '1:86327090390:web:ba82a6c08bc223a6fc3d77',
    messagingSenderId: '86327090390',
    projectId: 'loan-system-37b90',
    authDomain: 'loan-system-37b90.firebaseapp.com',
    storageBucket: 'loan-system-37b90.firebasestorage.app',
  );
}
